### ISSUE TITLE
Cypress app gets not installed when dependency is added using yarn

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-test-node-versions#6]
@fvanwijk commented on [Tue Sep 12 2017](https://github.com/cypress-io/cypress/issues/633)

- Operating System: OSX 10.12.6
- Cypress Version: 0.20
- Browser Version: n/a

### Is this a Feature or Bug?
Bug

### Current behavior:
I already have a working Cypress project and I upgraded to 0.20 by reinstalling it locally using `yarn`

```bash
$ yarn add -D cypress
```

Calling `npm cypress:open` (= `./node_modules/.bin/cypress open`) gives the error that Cypress is not installed yet. I have to install Cypress manually by calling `./node_modules/.bin/cypress install`.

### Desired behavior:
I want `cypress install` to trigger automatically after adding with `yarn` so that it can be opened immediately.

---

@bahmutov commented on [Tue Sep 12 2017](https://github.com/cypress-io/cypress/issues/633#issuecomment-328887813)

Hmm, we use `postinstall` script to actually install the binary

---

@bahmutov commented on [Wed Sep 13 2017](https://github.com/cypress-io/cypress/issues/633#issuecomment-329185632)

Might be related to Yarn bug https://github.com/yarnpkg/yarn/issues/853

**Comment by iganzina-epam** [comment]
Had similar issue, getting following error while running `yarn install` and having "cypress" dependency in package.json:

error Couldn't find package "@cypress/listr-verbose-renderer" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Couldn't find package "@cypress/xvfb" on the "npm" registry.


The reason was that in yarn global config I had our company's registry as a default one. So, adding “@cypress:registry” “https://registry.npmjs.org/” to .yarnrc and to .npmrc solved the issue.
